version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bhikku_registry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bhikku_registry
      SECRET_KEY: your-secret-key-change-in-production
      APP_ENV: development
      API_V1_STR: /api/v1
      STORAGE_DIR: /app/storage
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - storage_data:/app/storage
    depends_on:
      db:
        condition: service_healthy
    command: /bin/bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
  storage_data: